# Generated by Django 4.2 on 2023-08-14 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0006_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazvanie_regiona', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RequestedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('modification', models.CharField(max_length=255)),
                ('cost_of_ownership', models.IntegerField(default=0)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tax',
            name='Max_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tax',
            name='Min_power',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_requests', models.PositiveIntegerField(default=0)),
                ('average_ownership_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.requestedcar')),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Power', models.PositiveIntegerField(default=0)),
                ('Capacity_of_engine', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Nazvanie_modeli_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.model')),
            ],
        ),
        migrations.AddField(
            model_name='tax',
            name='Nazvanie_regiona_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cars.region'),
        ),
    ]
