# Generated by Django 4.2 on 2023-08-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_region_requestedcar_tax_max_power_tax_min_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='Nalog',
            field=models.IntegerField(default=0),
        ),
    ]
