# Generated by Django 4.2 on 2023-08-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_tax_nalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedcar',
            name='modification',
        ),
        migrations.AddField(
            model_name='requestedcar',
            name='power',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cars.modification'),
        ),
    ]
