# Generated by Django 4.2 on 2023-08-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_rename_power_requestedcar_modification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedcar',
            name='modification',
        ),
        migrations.AddField(
            model_name='requestedcar',
            name='modification_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestedcar',
            name='modification_power',
            field=models.IntegerField(default=0),
        ),
    ]
