# Generated by Django 4.2 on 2023-08-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_requestedcar_modification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedcar',
            name='requested_date',
        ),
    ]
