# Generated by Django 4.2 on 2023-08-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_remove_requestedcar_requested_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='average_ownership_cost',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='car',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='statistic',
            name='brand',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='statistic',
            name='model_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
