# Generated by Django 4.2 on 2023-09-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_requestedcar_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedcar',
            name='cost_of_fuel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestedcar',
            name='modification_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='requestedcar',
            name='probeg',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='requestedcar',
            name='rashod',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='requestedcar',
            name='region',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
