# Generated by Django 4.2 on 2023-09-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_requestedcar_cost_of_fuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedcar',
            name='probeg',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='requestedcar',
            name='rashod',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='requestedcar',
            name='region',
            field=models.CharField(default='', max_length=255),
        ),
    ]
