# Generated by Django 4.2 on 2023-09-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_alter_requestedcar_probeg_alter_requestedcar_rashod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedcar',
            name='probeg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestedcar',
            name='rashod',
            field=models.IntegerField(default=0),
        ),
    ]
