# Generated by Django 4.2 on 2023-09-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_alter_requestedcar_probeg_alter_requestedcar_rashod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedcar',
            name='cost_of_fuel',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='requestedcar',
            name='probeg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='requestedcar',
            name='rashod',
            field=models.FloatField(default=0),
        ),
    ]
