# Generated by Django 4.2 on 2023-09-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_alter_requestedcar_cost_of_ownership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedcar',
            name='sum_nalog',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='requestedcar',
            name='sum_of_fuel',
            field=models.FloatField(default=0),
        ),
    ]
