# Generated by Django 4.2 on 2023-09-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_requestedcar_sum_nalog_requestedcar_sum_of_fuel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedcar',
            old_name='sum_nalog',
            new_name='sum_of_nalog',
        ),
    ]
