# Generated by Django 4.2 on 2023-09-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_rename_sum_nalog_requestedcar_sum_of_nalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedcar',
            name='kolichestvo_zaprosov',
            field=models.IntegerField(default=1),
        ),
    ]
