# Generated by Django 4.2 on 2023-09-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_cardescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardescription',
            name='privod',
            field=models.IntegerField(choices=[(1, 'Полный'), (2, 'Передний'), (3, 'Задний')], default=1),
        ),
    ]
