# Generated by Django 4.2 on 2023-09-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_remove_cardescription_toplivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardescription',
            name='image',
        ),
        migrations.AddField(
            model_name='cardescription',
            name='first_image',
            field=models.ImageField(default='', upload_to='car_images/'),
        ),
        migrations.AddField(
            model_name='cardescription',
            name='main_image',
            field=models.ImageField(default='', upload_to='car_images/'),
        ),
        migrations.AddField(
            model_name='cardescription',
            name='salon_image',
            field=models.ImageField(default='', upload_to='car_images/'),
        ),
        migrations.AddField(
            model_name='cardescription',
            name='second_image',
            field=models.ImageField(default='', upload_to='car_images/'),
        ),
        migrations.AddField(
            model_name='cardescription',
            name='third_image',
            field=models.ImageField(default='', upload_to='car_images/'),
        ),
    ]
