# Generated by Django 4.2 on 2023-09-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0026_remove_cardescription_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardescription',
            name='name_of_car',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cardescription',
            name='privod',
            field=models.CharField(choices=[('Полный', 'Полный'), ('Передний', 'Передний'), ('Задний', 'Задний')], default=1),
        ),
        migrations.AlterField(
            model_name='cardescription',
            name='tip_kuzova',
            field=models.CharField(choices=[('Седан', 'Седан'), ('Внедорожник', 'Внедорожник'), ('Кроссовер', 'Кроссовер')], default=1),
        ),
    ]
