# Generated by Django 4.2 on 2023-10-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0030_alter_requestedcar_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedcar',
            name='region_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
