# Generated by Django 4.2 on 2023-10-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_requestedcar_region_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedcar',
            name='kolichestvo_zaprosov',
            field=models.IntegerField(default=1),
        ),
    ]
